keywords = {
    "vacation": {"project": "OOO", "task": "Vacation", "tag": ""},
    "vendor": {"project": "Tactical", "task": "Vendor Related Work", "tag": "Med"},
    "commute": {"project": "OOO", "task": "Traveling", "tag": ""},
    "1:1": {"project": "Strategic", "task": "1on1s", "tag": "Med"},
    "meeting": {"project": "Strategic", "task": "Meetings", "tag": "Med"},
    "town hall": {"project": "Strategic", "task": "Meetings", "tag": "Med"},
    "working group": {"project": "Strategic", "task": "Meetings", "tag": "Med"},
    "huddle": {"project": "Strategic", "task": "Meetings", "tag": "Med"},
    "stand up": {"project": "Strategic", "task": "Meetings", "tag": "Med"},
    "standup": {"project": "Strategic", "task": "Meetings", "tag": "Med"},
    "class": {"project": "Strategic", "task": "Training", "tag": "Med"},
    "SRE": {"project": "Tactical", "task": "TechOps", "tag": "High"},
    "doctor": {"project": "OOO", "task": "Doctor's Appointment", "tag": ""},
    "lunch": {"project": "Tactical", "task": "", "tag": ""},
    "lattice": {"project": "Tactical", "task": "Lattice", "tag": "Med"},
    "asana": {"project": "Tactical", "task": "Planning", "tag": "Low"},
}